name: Build and Push Image

on: [push, pull_request_target, workflow_dispatch]

env:
  GITHUB_REPO: "mildman1848/mod-infisical-cli"
  ENDPOINT: "mildman1848/mod-infisical-cli"
  BASEIMAGE: "universal"
  MODNAME: "infisical-cli"
  IMAGE_TAG: "0.1.3"

jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set Vars
        id: outputs
        run: |
          echo "GITHUB_REPO=${{ env.GITHUB_REPO }}" >> $GITHUB_OUTPUT
          echo "ENDPOINT=${{ env.ENDPOINT }}" >> $GITHUB_OUTPUT
          echo "BASEIMAGE=${{ env.BASEIMAGE }}" >> $GITHUB_OUTPUT
          echo "MODNAME=${{ env.MODNAME }}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
          # **** If the mod needs to be versioned, set the versioning logic below. Otherwise leave as is. ****
          MOD_VERSION=""
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_OUTPUT
    outputs:
      GITHUB_REPO: ${{ steps.outputs.outputs.GITHUB_REPO }}
      ENDPOINT: ${{ steps.outputs.outputs.ENDPOINT }}
      BASEIMAGE: ${{ steps.outputs.outputs.BASEIMAGE }}
      MODNAME: ${{ steps.outputs.outputs.MODNAME }}
      IMAGE_TAG: ${{ steps.outputs.outputs.IMAGE_TAG }}
      MOD_VERSION: ${{ steps.outputs.outputs.MOD_VERSION }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASS }}

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ needs.set-vars.outputs.ENDPOINT }}:${{ needs.set-vars.outputs.IMAGE_TAG }}
            ${{ needs.set-vars.outputs.ENDPOINT }}:latest
            ghcr.io/${{ needs.set-vars.outputs.ENDPOINT }}:${{ needs.set-vars.outputs.IMAGE_TAG }}
            ghcr.io/${{ needs.set-vars.outputs.ENDPOINT }}:latest